[theme]
base = "dark"

# General color setup
textColor = "#f0f0f0"
primaryColor = "#00C805"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#111111"

# Widgets
showWidgetBorder = true
borderColor = "#1f1f1f"

# Dataframes
dataframeHeaderBackgroundColor = "#111111"

# Base text
font = "'DM Sans':https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500&display=swap"
baseFontWeight = 400
baseFontSize = 14

# Heading text
headingFont = "DM Sans"
headingFontWeights = [700, 600, 500, 400, 400, 400]
headingFontSizes = ["2.2rem", "1.5rem", "1.1rem"]